version: '3'

services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    networks:
      - mynetwork

  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    networks:
      - mynetwork

networks:
  mynetwork: