version: '3'

services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    networks:
      - mynetwork

  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    networks:
      - mynetwork

  api:
    image: node:alpine
    ports:
      - "3000:3000"
    command: ["node", "-e", "require('http').createServer((req, res) => { res.end('Hello, World!') }).listen(3000)"]
    networks:
      - mynetwork

networks:
  mynetwork: